const phone='5491172365913';
const whatsapp=message=>`https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
document.querySelectorAll('.wa-link').forEach(link=>{link.href=whatsapp(link.dataset.message||'Hola, quiero consultar por Neo TV Digital Full.');link.target='_blank';link.rel='noopener';});
const moods={
  vivo:{tag:'EN VIVO',icon:'▣',title:'El mundo en vivo.',copy:'Una propuesta de canales y programación en vivo para toda la familia.',message:'Hola, quiero consultar por televisión en vivo.'},
  cine:{tag:'ON DEMAND',icon:'▶',title:'Historias para elegir.',copy:'Películas y series para disfrutar cuando quieras. Consultá las opciones disponibles.',message:'Hola, quiero consultar por películas y series.'},
  deportes:{tag:'DEPORTES',icon:'◉',title:'La emoción se vive.',copy:'Preguntanos por la programación deportiva y los eventos disponibles.',message:'Hola, quiero consultar por deportes y eventos.'},
  ayuda:{tag:'ACOMPAÑAMIENTO',icon:'✳',title:'Siempre del otro lado.',copy:'Si necesitás asistencia o asesoramiento, escribinos y recibí atención directa.',message:'Hola, necesito ayuda con el servicio de Neo TV.'}
};
const moodPanel=document.querySelector('#mood-panel');
const moodButtons=[...document.querySelectorAll('.mood')];
function setMood(key){const mood=moods[key],index=Object.keys(moods).indexOf(key)+1;moodPanel.dataset.mode=key;document.querySelector('#screen-tag').textContent=mood.tag;document.querySelector('#screen-icon').textContent=mood.icon;document.querySelector('#screen-index').textContent=`0${index} / 04`;document.querySelector('#screen-title').textContent=mood.title;document.querySelector('#screen-copy').textContent=mood.copy;const cta=document.querySelector('#screen-cta');cta.href=whatsapp(mood.message);cta.setAttribute('aria-label',`Consultar por ${moodButtons[index-1].querySelector('.mood-name').textContent}`);moodButtons.forEach(button=>{const active=button.dataset.mood===key;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});}
moodButtons.forEach((button,index)=>{button.addEventListener('click',()=>setMood(button.dataset.mood));button.addEventListener('keydown',event=>{if(event.key!=='ArrowDown'&&event.key!=='ArrowUp'&&event.key!=='ArrowRight'&&event.key!=='ArrowLeft')return;event.preventDefault();const step=event.key==='ArrowDown'||event.key==='ArrowRight'?1:-1;const next=moodButtons[(index+step+moodButtons.length)%moodButtons.length];setMood(next.dataset.mood);next.focus();});});setMood('vivo');
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.nav');menu.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(isOpen));menu.setAttribute('aria-label',isOpen?'Cerrar menú':'Abrir menú');});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menú');}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal').forEach((element,index)=>{element.style.transitionDelay=`${Math.min(index%4,3)*70}ms`;observer.observe(element);});
const progress=document.querySelector('.progress');let ticking=false;window.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max>0?scrollY/max*100:0}%`;ticking=false;});},{passive:true});
document.querySelector('#year').textContent=new Date().getFullYear();
