/* EGAM · catálogo de la demo.
   Los productos son REFERENCIAS de demo (rubros reales del negocio: frutos secos,
   deshidratados y vinos mendocinos). Precios: todos "a consultar" hasta que el
   cliente pase su lista. Listo para reemplazar por el catálogo de CobrOS. */
window.EGAM = {
  sellers: [
    { id: 'exequiel', name: 'Exequiel', phone: '5492622528672', show: '2622 52-8672' },
    { id: 'alexis',   name: 'Alexis',   phone: '5492622577848', show: '2622 57-7848' }
  ],
  ig: 'https://www.instagram.com/egam_frutossecos/',
  tiktok: 'https://www.tiktok.com/@exequiel.garcia1991',
  cats: [
    { id: 'frutos',  name: 'Frutos secos' },
    { id: 'deshi',   name: 'Deshidratados' },
    { id: 'semillas',name: 'Semillas y más' },
    { id: 'vinos',   name: 'Vinos' },
    { id: 'cajas',   name: 'Cajas y picadas' }
  ],
  pres: {
    granel: { menor: ['250 g', '500 g', '1 kg'], mayor: ['5 kg', '10 kg', 'Bolsa cerrada'] },
    vino:   { menor: ['Botella 750 ml'], mayor: ['Caja x6', 'Caja x12'] },
    caja:   { menor: ['1 caja'], mayor: ['10 cajas', '25 cajas', '50+ cajas'] }
  },
  products: [
    { id: 'almendras', cat: 'frutos', name: 'Almendras peladas', img: 'almendras', tag: 'Más pedido',
      desc: 'Almendra entera, crocante y pareja. La base de cualquier mix y la estrella de la picada.',
      uso: 'Picada, repostería, granola, leche vegetal o de a puñado.',
      aporta: 'Grasas buenas, vitamina E, magnesio y fibra.',
      conserva: 'Frasco hermético, lugar fresco y seco. En heladera dura más.' },
    { id: 'nueces', cat: 'frutos', name: 'Nueces mariposa', img: 'nueces', tag: 'Más pedido',
      desc: 'Mariposa clara, limpia de cáscara, lista para usar.',
      uso: 'Ensaladas, budines, alfajores, con queso y un tinto.',
      aporta: 'Omega 3 vegetal, antioxidantes y proteína.',
      conserva: 'Hermético y en heladera: la nuez se pone rancia con el calor.' },
    { id: 'nuecescascara', cat: 'frutos', name: 'Nueces con cáscara', img: 'nuecescascara',
      desc: 'Nuez entera con cáscara, para romper en la mesa.',
      uso: 'Mesas de fiesta, regalos, picadas rústicas.',
      aporta: 'Omega 3, fibra y minerales.',
      conserva: 'Bolsa de tela o canasto, lugar seco y ventilado.' },
    { id: 'castanas', cat: 'frutos', name: 'Castañas de cajú', img: 'castanas',
      desc: 'Cajú entera, de sabor suave y textura manteca.',
      uso: 'Snack, salteados, cremas y quesos veganos.',
      aporta: 'Hierro, zinc, magnesio y proteína.',
      conserva: 'Hermético, lejos del sol.' },
    { id: 'pistachos', cat: 'frutos', name: 'Pistachos tostados', img: 'pistachos',
      desc: 'Pistacho con cáscara abierta, tostado y salado justo.',
      uso: 'Aperitivo, helado, pastelería, con un blanco frío.',
      aporta: 'Proteína, potasio y vitamina B6.',
      conserva: 'Hermético, lugar fresco.' },
    { id: 'avellanas', cat: 'frutos', name: 'Avellanas', img: 'avellanas',
      desc: 'Avellana entera, perfumada, ideal tostada.',
      uso: 'Chocolatería, praliné, granola, picadas.',
      aporta: 'Vitamina E, grasas buenas y fibra.',
      conserva: 'Hermético, lugar fresco y seco.' },
    { id: 'mani', cat: 'frutos', name: 'Maní con cáscara', img: 'mani',
      desc: 'Maní tostado con cáscara, el clásico de siempre.',
      uso: 'Para la previa, la cancha o el partido en casa.',
      aporta: 'Proteína vegetal y niacina.',
      conserva: 'Lugar seco y ventilado.' },
    { id: 'mixclasico', cat: 'frutos', name: 'Mix clásico', img: 'mixclasico', tag: 'Mix',
      desc: 'Almendras, nueces, cajú, pistachos y maní en una sola bolsa.',
      uso: 'Snack de oficina, picada rápida, mochila.',
      aporta: 'Energía sostenida: grasas buenas + proteína.',
      conserva: 'Hermético, lugar fresco.' },
    { id: 'mixfrutal', cat: 'deshi', name: 'Mix frutal energético', img: 'mixfrutal', tag: 'Mix',
      desc: 'Frutos secos con pasas, arándanos y trozos de fruta deshidratada.',
      uso: 'Entrenamiento, trekking, desayuno con yogur.',
      aporta: 'Hidratos rápidos de la fruta + grasas de los frutos secos.',
      conserva: 'Hermético, lugar fresco y seco.' },
    { id: 'pasasrubias', cat: 'deshi', name: 'Pasas de uva rubias', img: 'pasasrubias',
      desc: 'Pasa sultanina dorada, dulce y carnosa.',
      uso: 'Pan dulce, arroz con leche, ensaladas, cuscús.',
      aporta: 'Hierro, potasio y energía natural.',
      conserva: 'Hermético; si se secan, se hidratan en agua tibia.' },
    { id: 'pasasmorochas', cat: 'deshi', name: 'Pasas de uva morochas', img: 'pasasmorochas',
      desc: 'Pasa negra de uva mendocina, sabor más intenso.',
      uso: 'Budines, rellenos, granola, con queso azul.',
      aporta: 'Antioxidantes, hierro y fibra.',
      conserva: 'Hermético, lugar fresco.' },
    { id: 'ciruelas', cat: 'deshi', name: 'Ciruelas desecadas', img: 'ciruelas',
      desc: 'Ciruela tiernizada, con o sin carozo según partida.',
      uso: 'Cerdo a la ciruela, compotas, desayuno.',
      aporta: 'Fibra y sorbitol: amigas del intestino.',
      conserva: 'Hermético, en heladera una vez abiertas.' },
    { id: 'orejones', cat: 'deshi', name: 'Orejones de damasco', img: 'orejones',
      desc: 'Damasco deshidratado, ácido y dulce a la vez.',
      uso: 'Picadas, carnes al horno, repostería, con un blanco.',
      aporta: 'Betacaroteno, potasio y fibra.',
      conserva: 'Hermético, lugar fresco.' },
    { id: 'higos', cat: 'deshi', name: 'Higos secos', img: 'higos',
      desc: 'Higo entero secado al sol, dulce y con semillitas crocantes.',
      uso: 'Con queso y nueces, en panes o solos con un tinto.',
      aporta: 'Calcio, fibra y potasio.',
      conserva: 'Hermético, lugar fresco y seco.' },
    { id: 'datiles', cat: 'deshi', name: 'Dátiles', img: 'datiles',
      desc: 'Dátil carnoso, naturalmente muy dulce.',
      uso: 'Endulzante natural, rellenos con almendra, licuados.',
      aporta: 'Energía rápida, potasio y magnesio.',
      conserva: 'Hermético; en heladera se mantienen tiernos.' },
    { id: 'arandanos', cat: 'deshi', name: 'Arándanos deshidratados', img: 'arandanos',
      desc: 'Arándano rojo deshidratado, dulce-ácido.',
      uso: 'Ensaladas, granola, muffins, mix de frutos secos.',
      aporta: 'Antioxidantes y vitamina C.',
      conserva: 'Hermético, lugar fresco.' },
    { id: 'bananachips', cat: 'deshi', name: 'Banana chips', img: 'bananachips',
      desc: 'Rodajas de banana crocantes.',
      uso: 'Snack de chicos, cereales, yogur.',
      aporta: 'Potasio y energía rápida.',
      conserva: 'Hermético para que no pierda el crocante.' },
    { id: 'chia', cat: 'semillas', name: 'Semillas de chía', img: 'chia',
      desc: 'Chía limpia, lista para hidratar.',
      uso: 'Pudding, panes, licuados, ensaladas.',
      aporta: 'Omega 3, fibra y calcio.',
      conserva: 'Frasco cerrado, lugar seco.' },
    { id: 'girasol', cat: 'semillas', name: 'Semillas de girasol peladas', img: 'girasol',
      desc: 'Girasol pelado, tostado o natural.',
      uso: 'Ensaladas, panes, barras de cereal.',
      aporta: 'Vitamina E y selenio.',
      conserva: 'Hermético, lugar fresco.' },
    { id: 'zapallo', cat: 'semillas', name: 'Semillas de zapallo', img: 'zapallo',
      desc: 'Semilla de zapallo con cáscara, tostada.',
      uso: 'Snack salado, topping de sopas y ensaladas.',
      aporta: 'Zinc, magnesio y proteína.',
      conserva: 'Hermético, lugar seco.' },
    { id: 'coco', cat: 'semillas', name: 'Coco rallado', img: 'coco',
      desc: 'Coco deshidratado rallado fino.',
      uso: 'Repostería, cocadas, granola, curry.',
      aporta: 'Fibra y grasas de cadena media.',
      conserva: 'Hermético, lejos de la humedad.' },
    { id: 'granola', cat: 'semillas', name: 'Granola artesanal', img: 'granola',
      desc: 'Avena tostada con frutos secos, semillas y fruta deshidratada.',
      uso: 'Desayuno con yogur o leche, bowls, snack.',
      aporta: 'Fibra, energía sostenida y proteína.',
      conserva: 'Hermético para que siga crocante.' },
    { id: 'malbec', cat: 'vinos', pres: 'vino', name: 'Malbec de Mendoza', img: 'malbec', tag: 'Alta gama',
      desc: 'La cepa emblema. Fruta roja madura, violetas y taninos amables.',
      uso: 'Asado, pastas con tuco, quesos semiduros, nueces e higos.',
      aporta: 'Servir a 16–18 °C. Abrir 20 minutos antes.',
      conserva: 'Botella acostada, lejos de la luz y del calor.' },
    { id: 'cabernet', cat: 'vinos', pres: 'vino', name: 'Cabernet Sauvignon', img: 'cabernet', tag: 'Alta gama',
      desc: 'Estructura y cuerpo: pimiento asado, cassis y un final largo.',
      uso: 'Cordero, carnes a la parrilla, avellanas y ciruelas.',
      aporta: 'Servir a 17–18 °C. Pide decantar.',
      conserva: 'Botella acostada, 12–16 °C ideal.' },
    { id: 'blend', cat: 'vinos', pres: 'vino', name: 'Blend de tintos', img: 'blend', tag: 'Alta gama',
      desc: 'Corte de cepas mendocinas, redondo y versátil.',
      uso: 'Para regalar o para la mesa larga del domingo.',
      aporta: 'Servir a 16–18 °C.',
      conserva: 'Botella acostada, lugar oscuro.' },
    { id: 'blanco', cat: 'vinos', pres: 'vino', name: 'Blanco de altura', img: 'blanco',
      desc: 'Fresco y aromático, con acidez de viñedo de altura.',
      uso: 'Pescados, quesos blandos, pistachos y orejones.',
      aporta: 'Servir a 8–10 °C.',
      conserva: 'Botella acostada; ya abierto, a la heladera con tapón.' },
    { id: 'rosado', cat: 'vinos', pres: 'vino', name: 'Rosado', img: 'rosado',
      desc: 'Liviano, frutado, ideal para días de calor.',
      uso: 'Picadas de verano, tapeo, arándanos y almendras.',
      aporta: 'Servir a 8–10 °C.',
      conserva: 'Botella acostada, lugar fresco.' },
    { id: 'picada', cat: 'cajas', pres: 'caja', name: 'Caja picada', img: 'picada', tag: 'Para regalar',
      desc: 'Un vino + frutos secos y deshidratados elegidos para acompañarlo.',
      uso: 'Cumpleaños, Día del Padre, una juntada con amigos.',
      aporta: 'La armás a tu gusto en "Armá tu caja".',
      conserva: 'Cada producto viene en su envase cerrado.' },
    { id: 'regalo', cat: 'cajas', pres: 'caja', name: 'Caja regalo empresarial', img: 'regalo', tag: 'Empresas',
      desc: 'Cajas para fin de año, clientes y equipos, en cantidad.',
      uso: 'Regalos corporativos, eventos, fiestas de fin de año.',
      aporta: 'Consultá personalización y tiempos de armado.',
      conserva: 'Cada producto viene en su envase cerrado.' },
    { id: 'cajaarmada', cat: 'cajas', pres: 'caja', hidden: true, name: 'Caja armada', img: 'picada',
      desc: 'Caja armada a medida desde "Armá tu caja".', uso: '', aporta: '', conserva: '' }
  ]
};
window.EGAM.list = window.EGAM.products.filter(p => !p.hidden);
