(function(){
  'use strict';
  const $=s=>document.querySelector(s),catalog=window.MazlCatalog;
  $('[data-year]').textContent=new Date().getFullYear();
  const menu=$('.menu-toggle'),nav=$('.nav');
  menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');nav.classList.toggle('open',open)});
  nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
  const grid=$('[data-products]'),status=$('[data-catalog-status]'),categories=$('[data-categories]'),count=$('[data-count]'),search=$('[data-search]'),sort=$('[data-sort]');
  let category='Todos';let cart=catalog.getCart();
  function currentList(){const q=search.value.trim().toLocaleLowerCase('es');let list=catalog.products.filter(p=>(category==='Todos'||p.category===category)&&(!q||(p.name+' '+p.description+' '+p.category).toLocaleLowerCase('es').includes(q)));if(sort.value==='price-up')list.sort((a,b)=>a.price-b.price);else if(sort.value==='price-down')list.sort((a,b)=>b.price-a.price);else if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));else list.reverse();return list}
  function renderProducts(){grid.replaceChildren();if(catalog.state!=='ready'){status.innerHTML=catalog.statusHTML();catalog.bindRetry(status,renderAll);count.textContent='';return}const list=currentList();status.textContent=list.length?'':'No encontramos productos con esos filtros. Probá otra búsqueda o consultanos por WhatsApp.';list.forEach(p=>grid.append(catalog.card(p,'cart')));count.textContent=list.length+' PRODUCTO'+(list.length===1?'':'S')+' PUBLICADO'+(list.length===1?'':'S')}
  function renderCategories(){categories.replaceChildren();if(catalog.state!=='ready')return;const names=['Todos',...new Set(catalog.products.map(p=>p.category))];names.forEach(name=>{const b=document.createElement('button');b.type='button';b.textContent=name;b.classList.toggle('active',name===category);b.setAttribute('aria-pressed',String(name===category));b.addEventListener('click',()=>{category=name;renderCategories();renderProducts()});categories.append(b)})}
  function renderAll(){renderCategories();renderProducts();renderCart()}
  catalog.load().then(renderAll);
  search.addEventListener('input',renderProducts);sort.addEventListener('change',renderProducts);
  grid.addEventListener('click',e=>{const b=e.target.closest('.add-product');if(!b)return;const p=catalog.products.find(x=>x.id===b.dataset.id);if(!p)return;cart[p.id]=(cart[p.id]||0)+1;catalog.saveCart(cart);renderCart();openCart()});
  const drawer=$('[data-cart-drawer]'),backdrop=$('[data-cart-backdrop]'),lines=$('[data-cart-lines]'),total=$('[data-cart-total]'),orderStatus=$('[data-order-status]');
  function openCart(){drawer.hidden=false;backdrop.hidden=false;document.body.classList.add('cart-is-open');$('.cart-close').focus()}
  function closeCart(){drawer.hidden=true;backdrop.hidden=true;document.body.classList.remove('cart-is-open')}
  document.querySelectorAll('.cart-open').forEach(b=>b.addEventListener('click',openCart));$('.cart-close').addEventListener('click',closeCart);backdrop.addEventListener('click',closeCart);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!drawer.hidden)closeCart()});
  function selected(){return Object.entries(cart).map(([id,quantity])=>({product:catalog.products.find(p=>p.id===id),quantity:Number(quantity)})).filter(x=>x.product&&x.quantity>0)}
  function renderCart(){lines.replaceChildren();const items=selected();if(!items.length){const p=document.createElement('p');p.className='empty-cart';p.textContent='Tu pedido está vacío. Sumá productos desde el catálogo.';lines.append(p)}items.forEach(({product:p,quantity})=>{const line=document.createElement('div');line.className='cart-line';const title=document.createElement('strong');title.textContent=p.name;const price=document.createElement('small');price.textContent=catalog.money(p.price*quantity);const controls=document.createElement('div');controls.className='cart-line-controls';const minus=document.createElement('button');minus.type='button';minus.textContent='−';minus.setAttribute('aria-label','Quitar una unidad de '+p.name);const amount=document.createElement('span');amount.textContent=String(quantity);const plus=document.createElement('button');plus.type='button';plus.textContent='+';plus.setAttribute('aria-label','Sumar una unidad de '+p.name);minus.addEventListener('click',()=>adjust(p.id,-1));plus.addEventListener('click',()=>adjust(p.id,1));controls.append(minus,amount,plus);line.append(title,price,controls);lines.append(line)});total.textContent=catalog.money(items.reduce((sum,x)=>sum+x.product.price*x.quantity,0));document.querySelectorAll('[data-cart-count]').forEach(n=>n.textContent=String(items.reduce((sum,x)=>sum+x.quantity,0)));$('[data-order-form] button[type=submit]').disabled=!items.length}
  function adjust(id,change){const p=catalog.products.find(x=>x.id===id);if(!p)return;const next=(cart[id]||0)+change;if(next<=0)delete cart[id];else if(!p.controlStock||next<=p.stock)cart[id]=next;catalog.saveCart(cart);renderCart()}
  $('[data-order-form]').addEventListener('submit',async e=>{e.preventDefault();const items=selected();if(!items.length)return;const form=e.currentTarget;const data=new FormData(form);const payload={nombre:String(data.get('nombre')||'').trim(),telefono:String(data.get('telefono')||'').trim(),email:String(data.get('email')||'').trim(),nota:String(data.get('nota')||'').trim(),items:items.map(x=>({productoId:x.product.id,cantidad:x.quantity}))};if(!payload.nombre||!payload.telefono)return;const button=form.querySelector('button[type=submit]');button.disabled=true;orderStatus.textContent='Registrando pedido…';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);let response;try{response=await fetch(window.MAZL.api+'/catalogo/'+encodeURIComponent(window.MAZL.slug)+'/pedido',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal})}finally{clearTimeout(timer)}const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error||result.message||'No se pudo registrar el pedido.');const summary='Hola MAZL.COM, registré un pedido a nombre de '+payload.nombre+': '+items.map(x=>x.quantity+' × '+x.product.name).join(', ')+'. Total: '+catalog.money(items.reduce((sum,x)=>sum+x.product.price*x.quantity,0))+'. Mi teléfono: '+payload.telefono+'.';cart={};catalog.saveCart(cart);renderCart();orderStatus.innerHTML='Pedido registrado. <a target="_blank" rel="noopener" href="'+catalog.wa(summary)+'">Abrir WhatsApp ↗</a>';window.open(catalog.wa(summary),'_blank','noopener');form.reset()}catch(err){orderStatus.textContent='No se pudo registrar el pedido: '+err.message+' Consultanos por WhatsApp antes de reintentar.'}finally{button.disabled=!selected().length}});
})();
