(function(){
  'use strict';
  const cfg=window.SUBLICAR;
  const $=(selector,root=document)=>root.querySelector(selector);
  const money=value=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(value);
  const wa=message=>'https://wa.me/'+cfg.whatsapp+'?text='+encodeURIComponent(message);
  const simplify=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const sectorOf=value=>{const text=simplify(value);if(/sublim|taza|personaliz/.test(text))return 'sublimacion';if(/bordad|textil/.test(text))return 'bordado';if(/3d|impresion|filamento/.test(text))return '3d';if(/electron|tecnolog|accesorio|celular/.test(text))return 'electronica';return 'otros'};
  const sectorNames={todos:'Todos',sublimacion:'Sublimación',bordado:'Bordado','3d':'Impresión 3D',electronica:'Electrónica',otros:'Otros'};
  const safeImage=value=>typeof value==='string'&&/^(https:\/\/|data:image\/(?:jpeg|png|webp|gif);base64,)/i.test(value)?value:'';
  const year=$('[data-year]');if(year)year.textContent=String(new Date().getFullYear());
  const menu=$('.menu-button'),nav=$('.nav');
  if(menu&&nav){menu.addEventListener('click',()=>{const opened=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(opened));menu.setAttribute('aria-label',opened?'Cerrar menú':'Abrir menú');nav.classList.toggle('open',opened)});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menú');nav.classList.remove('open')}))}

  const ideaForm=$('#idea-form');
  if(ideaForm){
    const preview=$('#idea-preview');
    const message=()=>{const data=new FormData(ideaForm);const sector=String(data.get('sector')||'Sublimación');const detail=String(data.get('detalle')||'').trim();const quantity=String(data.get('cantidad')||'').trim();return 'Hola Sublicar, quiero consultar por '+sector.toLowerCase()+'.'+(detail?' Mi idea: '+detail+'.':'')+(quantity?' Cantidad aproximada: '+quantity+' unidad(es).':'')};
    const render=()=>{preview.textContent=message()};
    ideaForm.addEventListener('input',render);ideaForm.addEventListener('change',render);
    ideaForm.addEventListener('submit',event=>{event.preventDefault();window.open(wa(message()),'_blank','noopener')});
    render();
  }

  if(document.body.dataset.page!=='catalogo')return;
  const grid=$('[data-products]'),status=$('[data-status]'),filters=$('[data-filters]'),count=$('[data-count]'),search=$('[data-search]'),sort=$('[data-sort]');
  const drawer=$('[data-cart-drawer]'),backdrop=$('[data-cart-backdrop]'),lines=$('[data-cart-lines]'),total=$('[data-cart-total]'),form=$('[data-order-form]'),orderStatus=$('[data-order-status]');
  const cartKey='sublicar-cart-v1';
  let products=[],state='loading',cart={},activeSector=new URLSearchParams(location.search).get('r')||'todos';
  if(!Object.prototype.hasOwnProperty.call(sectorNames,activeSector))activeSector='todos';
  try{const stored=JSON.parse(localStorage.getItem(cartKey));if(stored&&typeof stored==='object'&&!Array.isArray(stored))cart=stored}catch{}
  const saveCart=()=>{try{localStorage.setItem(cartKey,JSON.stringify(cart))}catch{}};
  const normalize=raw=>({id:String(raw._id||raw.id||''),name:String(raw.nombre||'').trim(),description:String(raw.descripcion||''),category:String(raw.categoria||'Otros'),sector:sectorOf(String(raw.categoria||'')+' '+String(raw.nombre||'')),price:Number(raw.precio)||0,image:safeImage(raw.foto),stock:Number(raw.stock),controlStock:Boolean(raw.controlaStock)});
  const clearStatus=()=>{status.hidden=true;status.replaceChildren()};
  const statusMessage=(title,body,retry=false)=>{status.hidden=false;status.replaceChildren();const heading=document.createElement('strong');heading.textContent=title;const paragraph=document.createElement('p');paragraph.textContent=body;const link=document.createElement('a');link.href=wa('Hola Sublicar, quiero consultar por un producto.');link.target='_blank';link.rel='noopener';link.textContent='Consultar por WhatsApp ↗';status.append(heading,paragraph,link);if(retry){const button=document.createElement('button');button.type='button';button.textContent='Reintentar';button.addEventListener('click',load);status.append(document.createTextNode(' '),button)}};
  async function load(){
    state='loading';grid.replaceChildren();statusMessage('Cargando catálogo…','Estamos buscando los productos publicados.');
    if(!cfg.slug){state='unavailable';products=[];renderFilters();renderProducts();renderCart();return}
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);
    try{const response=await fetch(cfg.api+'/catalogo/'+encodeURIComponent(cfg.slug),{signal:controller.signal});if(response.status===404){state='unavailable';products=[];return}if(!response.ok)throw new Error('Error de catálogo');const data=await response.json();products=Array.isArray(data.productos)?data.productos.filter(item=>item&&item.activo!==false).map(normalize).filter(item=>item.id&&item.name):[];state=products.length?'ready':'empty'}
    catch{state='error';products=[]}finally{clearTimeout(timer);renderFilters();renderProducts();renderCart()}
  }
  function visibleProducts(){const q=simplify(search.value.trim());const result=products.filter(item=>(activeSector==='todos'||item.sector===activeSector)&&(!q||simplify(item.name+' '+item.description+' '+item.category).includes(q)));if(sort.value==='price-up')result.sort((a,b)=>a.price-b.price);else if(sort.value==='price-down')result.sort((a,b)=>b.price-a.price);else result.sort((a,b)=>a.name.localeCompare(b.name,'es'));return result}
  function setSector(value){activeSector=value;const url=new URL(location.href);if(value==='todos')url.searchParams.delete('r');else url.searchParams.set('r',value);history.replaceState(null,'',url);renderFilters();renderProducts()}
  function renderFilters(){filters.replaceChildren();const keys=['todos','sublimacion','bordado','3d','electronica'];if(products.some(item=>item.sector==='otros'))keys.push('otros');keys.forEach(key=>{const button=document.createElement('button');button.type='button';button.textContent=sectorNames[key];button.classList.toggle('active',activeSector===key);button.setAttribute('aria-pressed',String(activeSector===key));button.addEventListener('click',()=>setSector(key));filters.append(button)})}
  function productCard(item){const card=document.createElement('article');card.className='product-card';const visual=document.createElement('div');visual.className='product-visual';if(item.image){const image=document.createElement('img');image.src=item.image;image.alt=item.name;image.loading='lazy';visual.append(image)}else{const marker=document.createElement('span');marker.textContent='✳';visual.append(marker)}const body=document.createElement('div');body.className='product-body';const category=document.createElement('span');category.className='product-category';category.textContent=item.category;const title=document.createElement('h2');title.textContent=item.name;const description=document.createElement('p');description.textContent=item.description||'Consultá los detalles de este producto.';const foot=document.createElement('div');foot.className='product-foot';const price=document.createElement('strong');price.textContent=item.price>0?money(item.price):'Consultar precio';const canAdd=item.price>0&&(!item.controlStock||item.stock>0);const action=document.createElement(canAdd?'button':'a');action.textContent=canAdd?'Sumar +':item.controlStock&&item.stock<=0?'Consultar stock ↗':'Consultar ↗';if(canAdd){action.type='button';action.addEventListener('click',()=>{cart[item.id]=(Number(cart[item.id])||0)+1;if(item.controlStock)cart[item.id]=Math.min(cart[item.id],item.stock);saveCart();renderCart();openCart()})}else{action.href=wa('Hola Sublicar, quiero consultar por '+item.name+'.');action.target='_blank';action.rel='noopener'}foot.append(price,action);body.append(category,title,description,foot);card.append(visual,body);return card}
  function renderProducts(){grid.replaceChildren();count.textContent='';if(state==='unavailable'){statusMessage('El catálogo online se está preparando.','La tienda se activará cuando Sublicar cargue sus productos en CobrOS. Mientras tanto, podés consultar cada sector por WhatsApp.');return}if(state==='empty'){statusMessage('Todavía no hay productos publicados.','Cuando se carguen en CobrOS van a aparecer acá automáticamente.');return}if(state==='error'){statusMessage('No pudimos cargar el catálogo ahora.','Probá de nuevo en unos segundos o escribinos por WhatsApp.',true);return}if(state==='loading')return;const list=visibleProducts();if(!list.length){statusMessage('No encontramos productos con esos filtros.','Probá otra búsqueda o consultanos directamente.');return}clearStatus();count.textContent=list.length+' PRODUCTO'+(list.length===1?'':'S')+' PUBLICADO'+(list.length===1?'':'S');list.forEach(item=>grid.append(productCard(item)))}
  const selected=()=>Object.entries(cart).map(([id,quantity])=>({product:products.find(item=>item.id===id),quantity:Number(quantity)})).filter(entry=>entry.product&&Number.isFinite(entry.quantity)&&entry.quantity>0&&entry.product.price>0);
  function renderCart(){lines.replaceChildren();const items=selected();if(!items.length){const empty=document.createElement('p');empty.className='cart-empty';empty.textContent='Tu carrito está vacío. Sumá productos desde el catálogo.';lines.append(empty)}for(const {product,quantity} of items){const line=document.createElement('div');line.className='cart-line';const name=document.createElement('strong');name.textContent=product.name;const subtotal=document.createElement('small');subtotal.textContent=money(product.price*quantity);const controls=document.createElement('div');controls.className='cart-controls';const minus=document.createElement('button');minus.type='button';minus.textContent='−';minus.setAttribute('aria-label','Quitar una unidad de '+product.name);minus.addEventListener('click',()=>adjust(product,-1));const amount=document.createElement('span');amount.textContent=String(quantity);const plus=document.createElement('button');plus.type='button';plus.textContent='+';plus.setAttribute('aria-label','Sumar una unidad de '+product.name);plus.addEventListener('click',()=>adjust(product,1));controls.append(minus,amount,plus);line.append(name,subtotal,controls);lines.append(line)}total.textContent=money(items.reduce((sum,entry)=>sum+entry.product.price*entry.quantity,0));$('[data-cart-count]').textContent=String(items.reduce((sum,entry)=>sum+entry.quantity,0));form.querySelector('button[type=submit]').disabled=!items.length}
  function adjust(product,difference){const next=(Number(cart[product.id])||0)+difference;if(next<=0)delete cart[product.id];else cart[product.id]=product.controlStock?Math.min(next,product.stock):next;saveCart();renderCart()}
  const openCart=()=>{drawer.hidden=false;backdrop.hidden=false;document.body.classList.add('cart-open');$('[data-close-cart]').focus()};
  const closeCart=()=>{drawer.hidden=true;backdrop.hidden=true;document.body.classList.remove('cart-open')};
  $('[data-open-cart]').addEventListener('click',openCart);$('[data-close-cart]').addEventListener('click',closeCart);backdrop.addEventListener('click',closeCart);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!drawer.hidden)closeCart()});
  form.addEventListener('submit',async event=>{
    event.preventDefault();const items=selected();if(!items.length||!cfg.slug)return;const values=new FormData(form);const payload={nombre:String(values.get('nombre')||'').trim(),telefono:String(values.get('telefono')||'').trim(),email:String(values.get('email')||'').trim(),nota:String(values.get('nota')||'').trim(),items:items.map(entry=>({productoId:entry.product.id,cantidad:entry.quantity}))};if(!payload.nombre||!payload.telefono)return;
    const submit=form.querySelector('button[type=submit]');submit.disabled=true;orderStatus.textContent='Registrando pedido…';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);
    try{const response=await fetch(cfg.api+'/catalogo/'+encodeURIComponent(cfg.slug)+'/pedido',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(result.error||result.message||'No se pudo registrar el pedido.'));const summary='Hola Sublicar, registré un pedido a nombre de '+payload.nombre+': '+items.map(entry=>entry.quantity+' × '+entry.product.name).join(', ')+'. Mi teléfono: '+payload.telefono+'.';cart={};saveCart();renderCart();orderStatus.replaceChildren(document.createTextNode('Pedido registrado. '));const whatsapp=document.createElement('a');whatsapp.href=wa(summary);whatsapp.target='_blank';whatsapp.rel='noopener';whatsapp.textContent='Avisar por WhatsApp ↗';orderStatus.append(whatsapp);if(typeof result.init_point==='string'&&/^https:\/\//i.test(result.init_point)){const payment=document.createElement('a');payment.href=result.init_point;payment.target='_blank';payment.rel='noopener';payment.textContent=' · Pagar online ↗';orderStatus.append(payment)}form.reset()}
    catch(error){orderStatus.textContent='No pudimos confirmar el pedido: '+(error.name==='AbortError'?'se agotó el tiempo de espera.':error.message)+' Revisá antes de volver a enviarlo o consultanos por WhatsApp.'}
    finally{clearTimeout(timer);submit.disabled=!selected().length}
  });
  search.addEventListener('input',renderProducts);sort.addEventListener('change',renderProducts);
  renderFilters();renderCart();load();
})();
